#!/bin/bash
# make the environment variable accessible to cron
env >> /etc/environment

# load the cronjob to the crontab
crontab /etc/crontab

# execute CMD
if [ "$api_mode" = "yes" ]; then
    echo "Start with API-MODE"
    uvicorn main:app --host 0.0.0.0 --port 8000
else
    echo "Start with CRON-MODE"
    exec "$@"
fi
