name: Publish to DockerHub/GitHub with a custom-tag
on:
  workflow_dispatch:
    inputs:
      tag:
        description: Name your tag
        default: test
        required: true  
jobs:
  update-dh:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to DockerHub with version-tag
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: abuhamsa/rogers2xmltv
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tag_names: true
    - name: Publish to DockerHub with latest-tag
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: abuhamsa/rogers2xmltv
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tags: ${{ github.event.inputs.tag }}
  update-gh:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to GitHub with version-tag
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: abuhamsa/rogers2xmltv
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: ghcr.io
        tag_names: true  
    - name: Publish to GitHub with latest-tag
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: abuhamsa/rogers2xmltv
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: ghcr.io
        tags: ${{ github.event.inputs.tag }}            
