name: Publish to GitHub with a verstion-tag and latest-tag
on:    
  release:
      types: [published]
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to GitHub with version-tag
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: abuhamsa/rogers2xmltv
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: ghcr.io
        tag_names: true  
    - name: Publish to GitHub with latest-tag
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: abuhamsa/rogers2xmltv
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: ghcr.io
        tags: "latest"       
